# Generated by Django 2.1.4 on 2018-12-17 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('mobileNUM', models.IntegerField()),
                ('diagonisis', models.CharField(max_length=2000)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'male'), (2, 'female')], default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleID', models.IntegerField()),
                ('refregator', models.IntegerField()),
                ('rackNUM', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
