# Generated by Django 2.1.4 on 2018-12-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='lineNum',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
